In [2]:
import numpy as np

In [3]:
t=np.random.random((2,2))

In [4]:
print(t)


[[0.22652091 0.74005751]
 [0.7947175  0.89377754]]


In [5]:
a = np.array([[5,6],[7,8]])
print(a)

[[5 6]
 [7 8]]


In [6]:
a = np.array([[5],[6],[7],[8]])
print(a)

[[5]
 [6]
 [7]
 [8]]


In [7]:
a = np.array([[5,8],[7,8]])
print(a)

[[5 8]
 [7 8]]


In [8]:
t.shape


(2, 2)

In [9]:
t.reshape

<function ndarray.reshape>

In [13]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [14]:
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [2]:
import numpy as np


In [3]:
x=np.linspace(2,15,20)

In [4]:
x

array([ 2.        ,  2.68421053,  3.36842105,  4.05263158,  4.73684211,
        5.42105263,  6.10526316,  6.78947368,  7.47368421,  8.15789474,
        8.84210526,  9.52631579, 10.21052632, 10.89473684, 11.57894737,
       12.26315789, 12.94736842, 13.63157895, 14.31578947, 15.        ])

In [5]:
y=np.linspace(2,30,20)

In [6]:
y

array([ 2.        ,  3.47368421,  4.94736842,  6.42105263,  7.89473684,
        9.36842105, 10.84210526, 12.31578947, 13.78947368, 15.26315789,
       16.73684211, 18.21052632, 19.68421053, 21.15789474, 22.63157895,
       24.10526316, 25.57894737, 27.05263158, 28.52631579, 30.        ])